#!/usr/bin/python3

import argparse
import subprocess
import sys
import os
import json
import re

# load config file
home_path = os.path.expanduser('~')
with open(f'{home_path}/.config/gamescope-manager/config.json', 'r') as config_file:
    config_data = json.load(config_file)

def run_pre_cmd(config_object):
    for key, value in config_object.items():
        match key:
            case "pre_cmd":
                subprocess.run(value, stdout=subprocess.DEVNULL)

def run_post_cmd_watcher(gamescope_output, config_object):
    if gamescope_output.startswith("env "):
        gamescope_output = gamescope_output[4:]
        env_var_pattern = r'\b\w+=(?:\"[^\"]*\"|\S+)'
        gamescope_output = re.sub(env_var_pattern, '', gamescope_output).strip()

    for key, value in config_object.items():
        match key:
            case "post_cmd":
                command = [f"{home_path}/.config/gamescope-manager/gamescope-post-cmd.sh", f'{construct_gamescope(config_object, True)}']
                command.extend(value)
                steam_env = os.environ.copy()
                subprocess.Popen(command, env=steam_env, start_new_session=True, stdout=subprocess.DEVNULL, stderr=subprocess.STDOUT)

def construct_gamescope(config_object, exclude_env=False):
    output = "gamescope"
    for key, value in config_object.items():
        match key:
            case "env":
                if exclude_env == True:
                    continue
                output = f"env {value} " + output
            case "backend":
                output += f" --backend {value}"
            case "resolution_w":
                output += f" -W {value}"
            case "resolution_h":
                output += f" -H {value}"
            case "refresh_rate":
                output += f" -r {value}"
            case "fullscreen":
                if value == True:
                    output += f" -f"
            case "force_grab_cursor":
                if value == True:
                    output += f" --force-grab-cursor"
            case "mangohud":
                if value == True:
                    output += f" --mangoapp"

    return (output + " --")

def run_fuzzel(config_object):
    fuzzel_cmd = ["fuzzel", "-d", "--minimal-lines", "--hide-prompt"]
    menu_options = []
    
    for key in config_object.keys():
        menu_options.append(key)

    fuzzel_cmd.append("-w")
    fuzzel_cmd.append(str(len(max(menu_options, key=len))))

    subprocess_printf = subprocess.Popen(["printf", '\\n'.join(menu_options)], stdout=subprocess.PIPE)
    user_choice = subprocess.run(fuzzel_cmd, stdin=subprocess_printf.stdout, stdout=subprocess.PIPE)
    return user_choice.stdout.decode('utf-8').strip()

if __name__ == "__main__":
    parser = argparse.ArgumentParser(prog="Gamescope Manager", description="A quick and dirty python script to manage multiple gamescope configurations")
    parser.add_argument('-t', '--tags', nargs="+")
    parser.add_argument('-i', '--include-untagged', action="store_true")

    args = parser.parse_args()
    if (args.include_untagged and args.tags == None):
        parser.error("-i has no effect without specifying tags")

    config_list = {}
    if args.tags != None:
        for key in config_data.keys():
            current_key = config_data.get(key)
            current_tags = current_key.get("tags")

            if current_tags != None:
                if any(x in current_tags for x in args.tags):
                    config_list.update({key: current_key})
            elif args.include_untagged == True:
                config_list.update({key: current_key})
    else:
        for key in config_data.keys():
            current_key = config_data.get(key)
            current_tags = current_key.get("tags")

            if current_tags == None:
                config_list.update({key: current_key})

    config_data = config_list

    user_choice = run_fuzzel(config_data)


    if user_choice == "":
        sys.stdout.write("true") # prepending the 'true' bash built-in is a great solution to cancel a game launch in steam as 'true' will eat all subsequent arguments provided
    else:
        selected_config = config_data.get(user_choice)
        run_pre_cmd(selected_config) 
        gamescope_output = construct_gamescope(selected_config)
        run_post_cmd_watcher(gamescope_output, selected_config)
        sys.stdout.write(gamescope_output) # output a properly formatted gamescope command to be passed to steam
